### ISSUE TITLE
[Unexpected Behavior] neither AMod nor MMod respects split DisplayBPM

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#100]
**What you're using**

Simfile that is mainly at 128BPM, but has one difficulty on split timing at 256BPM (and DisplayBPM set to 256).

**Expected behavior**

AMod and MMod should treat the difficulty as being at 256BPM.

**Actual behavior**

AMod and MMod treat the difficulty as being at 128BPM instead, making it scroll twice the correct speed.
![image](https://user-images.githubusercontent.com/8707990/92674913-ac850f00-f361-11ea-8e69-7d768b5d6033.png)
(A600 on the left, C600 on the right)

**Comment by Jousway** [comment]
@JapanYoshi I fixed the mmod part by changing it to check for displaybpm on steps instead of songs, and I fixed it so that amod checks the splitbpm but I talked with another dev member and they think we should keep amod the way it is, that it ignores the displaybpm and just taking the actual bpm of the chart (not song) because we basicly have mmod to do the displaybpm stuff, whats your opinion on this?

**Comment by JapanYoshi** [comment]
Sure, keep AMod broken if you like it broken /s

**Comment by Jousway** [comment]
as the original creator of AMod and talking with the dev team we desided to keep it like thi,s how is keeping a modifier that I created the way I want consider broken, also I dont spend an entire night (8 straight hours) fixing a bug to get a rude awnser when I expect a normal reply, so please refrain from that next time thanks.

**Comment by JapanYoshi** [comment]
AMod makes the most common scroll BPM the specified scroll speed, right?

If you keep it the way it is, at A600, this 256BPM chart would scroll at 1200 scroll speed.

This can't be intentional. This is broken.

**Comment by Jousway** [comment]
I think you're missunderstaning amod, which happens a lot, I've had this question a few time before.

basicly avarage mod takes all the bpm's, puts them in an array and checks which bpm is used for the most amount of ms in the song
so it then takels that bpm and changes the amod value to xmod because amod is just a function ontop of xmod, so the math is really easy `AMod / (CurBPM * Rate)` so an amod of 600 on a bpm of 256 results in an xmod of 2.34375, its basicly an easier xmod

**Comment by JapanYoshi** [comment]
This entire bug report shows that it’s NOT “like setting cmod but with all the chart effects”. You can clearly see and verify that A600 acts like C1200 when the chart’s main BPM is twice the song’s display BPM.

**Comment by Jousway** [comment]
`and I fixed it so that amod checks the splitbpm`
like I stated in my message I fixed that, maybe I should have elaborated more, it was a bug where p1 amod would get the value of p2 and do calculatons based on that, it was a mistake on my side, and I'm sorry for that, but it is fixed, the thing I wanted an opinion on was what you tought about it not using displayBPM but instead the splittiming BPM, so it calculates it based on the BPM the actual chart has, like AMod and MMod would do the exact same if both let them use displayBPM which is a waste to me
