### ISSUE TITLE
StepMania 5.3 Outfox Alpha Build 5.3.0 Crash

### ISSUE THREAD

**Issue by GMDParitionhlep** [TeamRizu/OutFox#12]
Missing folder/files etc...

I was just opening StepMania 5.3 Outfox Alpha Build 5.3.0 then it crashed due to an access violation..
Log: [log.txt](https://github.com/TeamRizu/OutFox/files/4806982/log.txt)
Crash info: [crashinfo.txt](https://github.com/TeamRizu/OutFox/files/4806980/crashinfo.txt)

Crash Video Zip: [CrashVideo.zip](https://github.com/TeamRizu/OutFox/files/4806985/CrashVideo.zip)

**Comment by Scraticus** [comment]
you will need to install a driver for your graphics card, as windows 10 has crippled your chipset.

**Comment by Scraticus** [comment]
There are two that have been known to work, for your specific chipset: we have the one from Dell, which is here: https://www.dell.com/support/home/en-uk/drivers/driversdetails?driverid=r279356 You may need to run it in 'windows 7 compatibility mode' but it will give you OpenGL 2.0

and this one which I have helped users with in the past on our discord server: https://cdn.discordapp.com/attachments/527732010714923019/701041468336242719/Win7Vista_64_151717bb.zip Again, this one needs to be run in windows 7 compatibility mode, as it cannot see windows 10.

The log says you have the Q45 intel chipset, but do you have any other graphics cards on the system?

**Comment by Scraticus** [comment]
There is a small possibility of this triggering an edge crash, which is why I've changed this to an issue we will be working on. We do not support D3D anymore, however, we do support ancient versions of OpenGL 1.1 to 1.5. This should also be exposed in your driver, but you will need to install one of the above to get access to this. Our new instance of D3D is at least a year away, so If we cannot get you fixed, it will be a shame for you to wait this long.

I will also change the way we sort things on the lowlevel window side.

**Comment by GMDParitionhlep** [comment]
It's okay, I'll just stick to StepMania 5.0.12 and older. Maybe in the future, I will switch to StepMania 5.3.

**Comment by moruzerinho6** [comment]
Have you tried installing the drivers?

**Comment by Scraticus** [comment]
This is an issue we cannot fix due to the driver crippling of the intel chipsets.

**Comment by GMDParitionhlep** [comment]
okay

**Comment by GMDParitionhlep** [comment]
i didn't need 5.3 anyways

**Comment by GMDParitionhlep** [comment]
i haven't responded nor did i agree to installing the needed drivers
because i worried it might kill my graphics card. (i mean i think there
will be a black screen)
