### ISSUE TITLE
[Nitpick] Axis problem with Wii Pad + GC Adapter

### ISSUE THREAD

**Issue by axu2** [TeamRizu/OutFox#135]
**Can't press up/down or left/right in Xinput**

Already had an official Konami Wii Pad and a Mayflash GC USB Adapter. They worked perfectly in Stepmania 5.0.12 but have an axis problem in outfox when I switched over a few days ago for much better framerates. The legacy input mode works fine without issues, so I'm using that for now, but wanted to let the dev team know in case this is unintended behavior for Xinput, since I'm sure this might frustrate a less informed user.

If it helps, in Xinput, pretty sure its being read as a Dpad. While in Legacy, just generic vJoy buttons.

**Comment by Scraticus** [comment]
Hiya @axu2! Thanks for taking the time to report this. This is a known fault of the GC adapter, so it's ok. Legacy is actually more HIDAPI, we just couldn't think of a better name to call it, they aren't vJoy buttons like on DirectInput btw!

Some of the really old controllers sadly do not get a correct allocation in XInput on any of the operating systems, which is why we rewrote the Input system to have the choice.

I will close this one, as it's nothing we can fix sadly, and yea, we have put up a tutorial on the matter.

Thanks again and let us know if you have any other issues.

**Comment by axu2** [comment]
Ah, Ok thanks I'll just stick with using Legacy then.
