### ISSUE TITLE
PLEASE PLEASE PLEASE release the sauce

### ISSUE THREAD

**Issue by teleshoes** [TeamRizu/OutFox#142]
im begging you to open it up with the next release. outfox a5.9 outstrips performance of other builds by like an order of magnitude, but i cant play it until i can apply my, like, 2 (idiosyncratic) patches. cant you just refuse support to folks who compile it themselves..? i promise i will never file a bug unless i can reproduce it on an official build...

it just seems so...anti-community to keep what i hear is increasingly beautiful source code all to yourselves so long....

**Comment by Scraticus** [comment]
Firstly, it took me a while to think about how to respond to this. The code is not suitable for release at this time, but it will hopefully be released fall/winter next year if all goes well.

I will emphasise this with a few comedic memes to lessen your disappointment.
![24ebcbe535da6a015e8cd14355c966d7](https://user-images.githubusercontent.com/11047768/97731271-d25ea280-1acc-11eb-8b24-4949fb4941b9.png)

or if you see us as evil raccoons:

![pD_VuFdad3kHTcmuFCi7B_O79xtKqPPA3AjovqJZh0rLaE_t6SCNU5eSEUvVsLJAbl9xTS6kZi0OE_1eGknj0uDBWxTnYOAhPJkO](https://user-images.githubusercontent.com/11047768/97731341-e60a0900-1acc-11eb-9c5d-454ccf231050.png)


The source will be opened when it's ready, but i hope this doesn't detract from you playing the game. You also could, you know, give us details of these 'patches' that you speak of above, as we are not against adding options which can benefit the community to the game.

I await your reply before closing.

Squirrel

**Comment by moruzerinho6** [comment]
![image](https://user-images.githubusercontent.com/58047457/97731352-c4505800-1ab3-11eb-8b11-d6f55bb0db44.png)

**Comment by teleshoes** [comment]
sigh.....closed-source forks of open-source projects considered harmful

i assume the true motivation is that you dont want competing forks to adapt only half of your improvements, and thus fracture the codebase more? i think you guys have demonstrated that there is only one fully-featured, backwards-compatible, performant fork worth anyone's time....that is, it WOULD be worth the community's time if the community were allowed in...

p.s.: cmon, it will NEVER be "ready". if your current goals for release require a YEAR, that means the goals will keep expanding forever until dev stalls. what kind of assurance can you give the community that it wont just drag out forever until stepmania is officially closed source?

**Comment by teleshoes** [comment]
as for things i reaallly want (but have no particular right to ask for, and would just do myself if...):
-i want a pulseaudio enabled build
-i want an option to disable input from the pad in the menu to not change difficulty. this might be doable in the lua, not sure
-i want to dump more detailed stats about each song to a log file after each play (this can definitely be in the theme lua)
-and most particularly (and weirdly) i want to count jumps/hands as a single note for the upload w2/w3/w4 counts, like ddr does. (theres only one judgment per row, why are there 2 "Marvellous"es counted per row for my exscore/pct?)

**Comment by SheepyChris** [comment]
- PulseAudio is already available if you define `SoundDrivers` in `Save/Preferences.ini` as `Pulse`;
- There is an option in the default theme to utilize only dedicated menu buttons, avoiding difficulty or song changes from pad input;
- That feature would be theme related and is already available in, for example, our [Simply Love fork](https://github.com/Tiny-Foxes/Simply-Love-OutFox);
- There is also an option in the default theme to count jumps/hands as a single combo and not per note.

I would recommend poking more around the game and be sure that your suggestions/complaints are already in. 🙂

**Comment by teleshoes** [comment]
- pulseaudio: YAY! thanks
- dedicated-menu-buttons option: that doesnt prevent changing DIFFICULTY, only changing SONGS
- detailed-score-info: yes, i said that, i know i can write it with a lua script. i had written it in cpp in stepmania 3.9 or 5.0, is all
- count jumps/hands notes: im not talking about combo. im talking about note count per timing window e.g.: (364 Fantastic, 173 Perfect, 3 Great, 2 Good, 1 Miss). if that setting is supposed to fix the timing-window-counts, it doesnt work, or im crazy


"I would recommend poking more around the game" yes yes, i agree! in fact, i wasnt making these feature requests or complaints. i mentioned only because squirrel told me to say what kinds of things i was looking to do in the source (and honestly, the biggest one is to look in the source and find out what i want to change)

**Comment by LightningSkunk** [comment]
> sigh.....closed-source forks (etc...)
> …What kind of assurance can you give the community (etc...)

There are many very good reasons in my opinion that Squirrel and Team Rizu have for keeping this project closed source for the aforementioned time-frame. I became a regular on the Moondance Discord and a significant Patreon supporter only because of their wisdom, skill, foresight, and commitment to giving back and supporting the community for today and tomorrow. In my opinion, keeping the project closed-course for another year is still very much in the best interest of the community. If the above replies from Squirrel and SheepyChris don't have you convinced already, if you hang out in the Moondance Discord long enough in good faith, I suspect  that your fears will be well assuaged :)

**Comment by teleshoes** [comment]
actually that WAS a somewhat reassuring answer, thank you. although i still dont see the value to the community

**Comment by LightningSkunk** [comment]
> although i still dont see the value to the community

"outfox a5.9 outstrips performance of other builds by like an order of magnitude,"

You are already seeing the value being given to the DDR/ITG/Para community by the project being temporarily closed source. That performance increase, as well as unmatched controller support, are just the tip of the iceberg. These things alone would not have been possible had it been open source, and cannot improve further AND support the community for tomorrow if open-sourced now given the state of much of the core code still. This is an ambitious project that requires a great deal of skill and specialized knowledge for a small team to do well. 

But seriously, hang out on the Moondance Discord and I think you'll see more of the value creation and community (re)building that has only been possible by it being temporarily closed source. Sometimes its hard to put sufficient explanation in a forum post at a given project stage ;)

**Comment by ColonelPanicks** [comment]
While increased performance and adaptability is a benefit for the community I've gotta admit that it still is not a good look. 

Also, closing the source of the project and making money (via patreon) literally goes against the original licensing of Stepmania (which this project is based off of - see attached screenshot from Stepmania GitHub page).

<img width="823" alt="Screenshot 2020-11-01 at 11 44 09" src="https://user-images.githubusercontent.com/27725639/97801877-baeff880-1c37-11eb-93d0-bbaf06e5ea12.png">

Violating the above seems like a disservice to the community and everyone that originally contributed.

## The FAQ

I noticed [the FAQ](https://projectmoon.dance/faq) on your website has extensive reasoning for why the code is closed source, I think it's worth addressing some of the holes in those arguments

> allowing source code access at this time would allow users to compile their own builds based on incomplete work, which would be difficult for us to debug and support during this phase of development..

You do not need to support random branch builds, literally every big open-source project (inlcuding Linux OSes, desktop managers and the like) have all of their development branches and everything open. This does not create much additional support load and, honestly, there is no requirement for support from the core team (this is were the _community_ comes in), you can simply say that you'll "only provide debug support for tagged/released versions".

> SSC [Spinal Shark Collective, the 5.0.x development team] did this same behaviour before us, so we did not see it as a problem

This is an excuse, not a reason. Be better than them.

## Other Comments Here

To respond to some of the points made in other comments here.

>  if you hang out in the Moondance Discord long enough in good faith, I suspect that your fears will be well assuaged

I'm new to the discord but the passion and focus of the team is undeniable however this doesn't detract from what is essentially nicking previously FOSS for personal gain, I have no issue with making money from FOSS but to take existing FOSS, modify and close-source it and then profit? That's an Oracle-level move!

> You are already seeing the value being given to the DDR/ITG/PIU/Para community by the project being temporarily closed source.

I don't see how being open-source would prevent development. As mentioned earlier the team can focus on what they want, keeping the code open is just honouring the original intention of the software and allowing others to experiment. 

> cannot improve further AND support the community for tomorrow if open-sourced now given the state of much of the core code still. 

Communities support themselves, that's why a Discord server exists, that's why forums exist. I understand that the core team could feel a pressure or a responsibility to support everyone (which I appreciate) but to say that opening the source code would cease development is a rather weak excuse when compared to literally every single other FOSS project that exists, works and develops...

> This is an ambitious project that requires a great deal of skill and specialized knowledge for a small team to do well.

I've had a few attempts at beginning to understand the StepMania codebase and cannot agree more that it takes specialised skill and knowledge! The core team behind this are clever individuals with a wonderful passion but, again, this is no excuse for closing off the source code.

## Conclusion

Honestly, I like this project and it's good to see the revival of loving development going into Stepmania but, as a lover and supporter of FOSS, this is nothing but suspicious. 

I'd also love to support this project but cannot bring myself to support it vocally or financially in good faith when it seems like an effort to profit off of a previous project while removing the FOSS side of it that made the community in the first place.

**Comment by Scraticus** [comment]
I think this has gone off topic, and accusing us of profiteering doesn't help anyone. The Patreon _donations_ pay for our servers and testing/development. We do not take a wage. And if we were to profit it would be off of OUR work. You have completely dismissed the fact we have worked on this project for 2 years, and the fact people wish to donate to further that work makes us 'oracle'. 

I'm closing this issue as this is going to turn into people trying to bring the team down and that is not what this issue tracker is for.

**Comment by teleshoes** [comment]
@Scraticus you're aware that you can make the source AVAILABLE, and NOT accept pull requests right? just make a policy that you will close or ignore any and all pull reqs, and that you will close any ticket that doesnt list an official build.

source-available, closed-to-contribution is a fairly popular model, actually, and it would INSTANTLY assuage all doubts from past contributors like me may have about your ultimate intentions. (in fact, the thing that scares me the most is that somehow the team just falls apart, the work is abandoned and all the work you guys have done never see the light of day, or, worse, that you find excuses to keep the source closed forever because its been so convenient for so long)


as for using github-without-pullreqs, here is what gnome did to use github while forcibly ignoring pullreqs, and some more suggestions.
https://mail.gnome.org/archives/desktop-devel-list/2016-November/msg00043.html
https://github.com/isaacs/github/issues/1191#issuecomment-375486285




as an aside, kernelpanics was NOT off topic; it LOOKS really bad to accept donations for continuing work on an open-source project after you close it, with only your word that you will re-open it, REGARDLESS of whether you are in fact trustworthy.

but most importantly: **after seeing the level of support you have and the team's obvious dedication and clear results, i personally do not doubt that your intentions are completely honest.** it was not my intention to make a ticket for berating the team. (however, you cant deny that closing the source invites people to speculate as to motivation, especially when the reasons given **MAKE NO SENSE**)
