### ISSUE TITLE
[BUG] "use only dedicated buttons" for difficulty selection

### ISSUE THREAD

**Issue by teleshoes** [TeamRizu/OutFox#158]
the option "use only dedicated buttons" for song-select screen does NOT prevent up-up or down-down on the dancepad from changing the difficulty.
it would be GREAT if there were three choices for this option: `Pad+Keyboard for all`, `Keyboard for all, Pad for difficulty`, `Keyboard only`

OR just one new option, completely independent of the current option:
`allow changing difficulty with double-tap up/down game input`

use case: i stand on the up arrow when selecting songs and my stupid omega gx renders a double tap every time i lift my full weight off the up arrow. (l-tek is in the mail....). this means i have to change the difficulty virtually every song selection

**Comment by teleshoes** [comment]
this is really a feature request, but the option does say 'dedicated buttons only', so its kind of a bug?

**Comment by teleshoes** [comment]
this is my actual proposal for the config UI (first option is unchanged, second option is brand new, both are independent):

#### MENU BUTTONS `[Use Gameplay Buttons]` `[Only Dedicated Buttons]`
```
Choose between allowing game buttons (dance pad, etc.) and Menu* buttons
for menu movement. Be sure to map the Menu* set of buttons before setting
this to "Only dedicated buttons"!
```

#### DIFFICULTY BUTTONS `[Double-tap Gameplay Buttons]` `[Menu Buttons Only]`
```
Choose between allowing UP and DOWN game buttons (dance pad, etc.) to change the
difficulty. If set to "Menu buttons only" changing the difficulty is possible
only with the mapped Menu* set of buttons.
```

and the option would be: `DifficultyButtonsDoubleTapGameplay=0` or something

**Comment by ListenerJubatus** [comment]
As mentioned on Discord, this is the intended behavior. This is meant to emulate arcade DDR/ITG behavior of only letting you manipulate the menus with the dedicated (read: cabinet) buttons. In both cases, the double-tap code on the pad is how you change difficulty because ITG and _most_ DDR games of the era (barring DS Euromix 2) did not use a two-step "select song then select difficulty" workflow (though newer DDR games, as well as Pump, do).

Are you sure this isn't an issue with your pad?
