### ISSUE TITLE
[BUG] Dance pad not working propertly - not configured and not able to press more than one button at the same time

### ISSUE THREAD

**Issue by robertvalik** [TeamRizu/OutFox#195]
**Please give System Info**

OS: *Linux*

CPU: *Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz*

00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 630 (Mobile)
01:00.0 VGA compatible controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)

Storage: *SSD/HDD*

**Please give your StepMania Info**

StepMania Version: *Stepmania-Outfox-Alpha-4.9.6-amd64-date-20201216*
Theme: *Nooo idea, probably default?*

**Describe the problem**

Dance pads are not usable. I have been using these pads for the last cca 12 years with various versions of Stepmania on various systems (Linux 32bit, Windows, Max OS X, Linux 64bit) without any problem or manual configuration. lsusb:

Bus 001 Device 013: ID 6677:8811 WiseGroup, Ltd. Deluxe Dance Mat

After recent update from 4.3 to 4.9.6 they stopped working. Stepmania still recognizes them:

Outfox Engine: Legacy Joystick subsystem - Found 1 joysticks
Outfox Engine: Legacy Joystick subsystem - Joy device added
Outfox Engine: Legacy Joystick subsystem -   0: 'WiseGroup.,Ltd Positive Gaming Impact USB pad' axes: 2, hats: 0, buttons: 10

But they are not working. I have to map them (I have used this method https://projectmoon.dance/help/controllers). After mapping, I can use the pad for browsing menus, but it is not usable in the game as only one button is recognized (if I stand on the left arrow, every other button is ignored and so).

I tried to switch to Xinput in the experimental settings but after that the pad controls cannot be mapped anymore.

**Describe what should happen**

Pad should be recognized, working and it should be possible to press every four arrows at the same time.

**Logs and Additional context**

1. Go into the game folder
2. Open the Logs folder - I dont seem to have that folder?

**Comment by Scraticus** [comment]
can you post the full log info?

we need the full log.txt to help you further

**Comment by robertvalik** [comment]
[log.txt](https://github.com/TeamRizu/OutFox/files/5753564/log.txt)

Slight update, while creating the log, I have found out that it is not as simple as it seemed (the song I was playing in previous attempt starts with some combination of left/right arrows and I did not try anything other). In reality, only the right arrow is blocking the left one.

When I stand on the right arrow, the jumping on left arrow has no effect. 

If I stand on the left arrow, jumping on the right one correctly registers but it also triggers the left arrow...

I did not notice any other weird combinations.

**Comment by Scraticus** [comment]
would ikt be possible for you to join our discord? it's going to be easier to explain and sort out via voice, as this is a clear axis map issue which needs XInput to solve.

sometimes just being able to show and see is easier than explaining via text 
(and i know our controller mapping tutorial sucks bad, i'm going to fix it)

**Comment by robertvalik** [comment]
The problem is caused by the X-Box gamepad support kernel module (xpad) intercepting the events and messing up input for Stepmania. The workaround is to manually set correct values in Save/Keymaps.ini (in my case "Joy1_Button _X_" and "Joy2_Button__X_" for the second pad).

Thank you very much for the help on Discord :-)

**Comment by Scraticus** [comment]
Indeed, i'll write up the how-to here and get it added to the site.

**Comment by Scraticus** [comment]
## XInput Interfering with HIDAPI Mode, and Breaking Axis Pads

If you have an axis pad which is showing two sets of buttons, or simply just cancelling out, and you cannot seem to map it in game, this is what you need to do to fix it.

The pad showing two buttons will look like this:

![image](https://user-images.githubusercontent.com/11047768/103447952-575f6700-4c8a-11eb-9c48-c7c72a3d969a.png)

I am pressing the left Arrow, but getting two sets of inputs. On Linux and MacOS, this can be due to an installed xbox360 driver, or the xpad module intercepting the events, and reporting an axis anyway.

The next patch of OutFox mitigates this issue a little bit, but it still is a pain.

To fix this, you need to write down the BUTTON numbers shown on screen, so you get a list for all four arrows:

`Down=Joy1_Button 2
Left=Joy1_Button 1
Right=Joy1_Button 4
Up=Joy1_Button 3`

***Make sure that you close the game!*** 
You can now navigate to your save folder, and look for your `keymaps.ini` file and set the buttons manually, so you can basically ignore the axis values given by the xpad driver. you need to add the mapping before the ::: as shown below:

![unknown](https://user-images.githubusercontent.com/11047768/103448007-2f243800-4c8b-11eb-95ca-a6a1d47a0802.png)

You can save this, and then start the game again, and your pad will be mapped.
