### ISSUE TITLE
[BUG] GAME CRASHED WHEN STARTING

### ISSUE THREAD

**Issue by ArielleTolome** [TeamRizu/OutFox#203]
**Please give System Info**

OS: MacOS

CPU: Apple Silicon M1

GPU: Apple Silicon M1

Storage: 512GB

**Please give your StepMania Info**

StepMania Version: StepMania 5.3 Alpha 4.9.6
Theme: Project Moondance

**Describe the problem**

When I tried loading StepMania app, it says that the game crashed with a popup error.

**Describe what should happen**

StepMania app should be loading with a game screen.

**Logs and Additional context**

StepMania5.3-git-692655e77f crash report (build 692655e77f, 20201216 @ 19:12:33)
--------------------------------------

Architecture:   Mac OS X (Arm M1)
Crash reason:   Segmentation fault - invalid permissions at 0x0000000000000008
Crashed thread: main

Checkpoints:
Thread: main
        IniFile.cpp:21 Reading 'Data/Defaults.ini'
        IniFile.cpp:21 Reading 'Save/Preferences.ini'
        IniFile.cpp:21 Reading 'Save/Preferences.ini'
        IniFile.cpp:21 Reading 'Data/Static.ini'
        IniFile.cpp:21 Reading 'Data/Static.ini'

Static log:
StepMania5.3-git-692655e77f
Compiled 20201216 @ 19:12:33 (build 692655e77f)
Log starting 2021-01-23 12:05:24
Loading window: sdl

Partial log:
00:00.018: Reading 'Data/Static.ini' failed: No such file or directory
00:00.019: StepMania5.3-git-692655e77f
00:00.019: Compiled 20201216 @ 19:12:33 (build 692655e77f)
00:00.019: Log starting 2021-01-23 12:05:24
00:00.019:  
00:00.019: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.020: Reading 'Data/Static.ini' failed: No such file or directory
00:00.020: Reading 'Data/Static.ini' failed: No such file or directory
00:00.147: Outfox Engine: SDL Subsystem Initialised.
00:00.172: Loading window: sdl

-- End of report

**Comment by Scraticus** [comment]
![4v048a](https://user-images.githubusercontent.com/11047768/105610028-fddbeb00-5da4-11eb-8c43-dd1767693ac6.jpg)

You did not dequarantine the application prior to running, as part of the FAQ, [here](https://projectmoon.dance/faq)

Scroll down to the MacOS section and enter the command.

We are in the process of signing the application (which as an indie developer is a pain due to the costs) so this step won't be required anymore.

We've had a lot of Apple users with this issue so don't worry, you're not the first to skip reading.

**Comment by ArielleTolome** [comment]
WORKING PERFECTLY THANK YOU SO MUCH A+++++

**Comment by Scraticus** [comment]
awesome, have fun with the game!
