### ISSUE TITLE
[BUG] Weird graphic behavior.

### ISSUE THREAD

**Issue by igormclven** [TeamRizu/OutFox#219]
Hi guys, thanks for your effort! :3

When I try to play from my laptop with intel integrated graphics (intel 620) I see this:

![bug](https://user-images.githubusercontent.com/8197834/109010713-209c4080-767e-11eb-8bd9-a85dfaa3c153.png)

It's interesting because the glitch will be throughout the game, but if I set it to full screen then it works fine.

This has been present in the last versions (three or two releases, I don't remember :c).  With older versions it does not fail, neither with SM 5.2, 5.1 etc... 

I have:
Windows 20H2
Core i5 7th
Intel HD 620
Dual monitor.

**Comment by Scraticus** [comment]
This is actually an intel driver bug, with the fact we have a new presentation window. I'd need to see a log to confirm, however it's usually fixed with a driver update. or swapping renderer. You likely wouldn't have seen it on previous versions as they defaulted to directx, not opengl, which is our default.

**Comment by igormclven** [comment]
Ohh wow, I understand. Okay I'll check.
