### ISSUE TITLE
F3 ScreenGameplay restart crashes (overflow?)

### ISSUE THREAD

**Issue by PCBoyGames** [TeamRizu/OutFox#23]
!m_pSoundMusic->IsMusicPlaying() failed assertion occupies the crash reason when using the F3 gameplay restart. Squirrel tells me it’s trying to play a null sound, but now it’s seeming strangely likely to be more than that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Scraticus** [comment]
Confirmed, this doesn't seem to have a fully completed codepath, however, we can utilise the options from the pause menu with some checks to do this properly in the future.

The sound and thread overflow and cause a race condition in the current code, and this behaviour just needs to be programmed into that path.

Another rabbit hole worthy bug :)

**Comment by Scraticus** [comment]
I'm not sure what we're going to do on this one.

Talking to some of the older developers, it seems the code was never written to reset gameplay using the operator menu. I mean why would you ever need to when we have pause?

I'm going to talk with the team on a solution, it is a bug due to the crash, but we need to decide to disable it, or to maybe write a new codepath for it.

**Comment by JoseVarelaP** [comment]
Figured out what happened here. Audio was getting into a position where it would be impossible to play anymore, so that's dealt with.
