### ISSUE TITLE
Theme causing arrows to change BPM?

### ISSUE THREAD

**Issue by Yuberz** [TeamRizu/OutFox#302]
Whenever I use [this theme](https://youtu.be/5tUfvuB0g-U), the left and right arrows in game causes the scroll speed to increment up and down (faster with right arrow and slower with left arrow). Even remapping the keys of left and right arrow don't make it stop. I'm not sure what causes it, but the game plays fine without the theme.

**Comment by JoseVarelaP** [comment]
This is not an OutFox issue, this is the theme having special functions to change the speed and cover lane distance with the *Menu* buttons. It seems you don't have dedicated buttons set first and declared, so they're acting as both at the same time, which is the default for regular themes, not a lot of themes do this.

To enable dedicated keys, go to in the input options (Input options > Advanced Input Options) and change Dedicated Menu Buttons to "Dedicated Buttons". ***Ensure you already have set dedicated buttons before this is changed however, otherwise, you won't be able to move through the menus!***

The theme performs change of speeds via Code messages done in its metrics.
```ìni
CodeSpeedUp="MenuRight"
CodeSpeedDown="MenuLeft"
```
