### ISSUE TITLE
[BUG] Windows 10 Microsoft Defender causing Cache to not work after restart

### ISSUE THREAD

**Issue by axu2** [TeamRizu/OutFox#329]
**Please give System Info**

OS: *Windows 10*

Storage: *SSD*

**Please give your StepMania Info**

StepMania Version: *Any Stepmania version, including 5.0.12 and Outfox*

**Describe the problem**

When I played Stepmania on Windows 7, starting Stepmania would be really fast after the initial cache build.
The initial cache build would maybe take maybe a minute with around 1000 songs.
Afterward starting Stepmania would only take a few seconds. I'd estimate this to be around a 10x difference in loading time.

This might not sound like a big time difference, but if a user had say 20K songs, this 10x difference could become huge.

When I play on Windows 10, the cache feature only partially works.

After the initial cache build, Stepmania loads really fast as long as I don't restart my computer.

But if I do restart my computer, starting Stepmania again takes as long as a initial cache build.
I'm not really sure what's it's doing. Maybe its rebuilding the cache. Maybe it's being scanned by Windows 10 Defender.

The solution is to add the Stepmania cache folder to be excluded from Windows 10 Defender Security scans,
documented here: 

https://github.com/stepmania/stepmania/wiki/Install-Guide#windows

![image](https://user-images.githubusercontent.com/20757319/117909970-f7a84680-b28f-11eb-92db-ff708876120d.png)

**Describe what should happen**

Stepmania would ideally not require a user to jump through this extra hoop to get fast loading times.

https://www.reddit.com/r/Stepmania/comments/n53b62/windows_10_how_to_make_songs_load_super_fast_1/

A user on reddit reported that he loaded 20k songs in 30 seconds after changing this security setting.

Before, he probably had to wait several minutes to start up Stepmania.

Is this possible to do? Otherwise, it really should be documented so users can actually see it when downloading Outfox.

**Comment by SheepyChris** [comment]
No third-party software will ever be able to modify Windows Defender's settings to accommodate for higher performance, as that would become a severe security risk to the operating system and user data. The way that Defender interferes with OutFox and older builds of StepMania is completely up to Microsoft and beyond our reach. If you're interested in having a better experience with the game, I would personally recommend utilizing a Linux distribution since it does not have any of the intrusive actions and performance penalties that Windows 10 carries today. With a Celeron G4900 and an SSD running MX Linux, I am able to load 4k songs in under 3 seconds, way ahead of what W10 could ever provide with the same hardware.

**Comment by SHRMP0** [comment]
> Is this possible to do? Otherwise, it really should be documented so users can actually see it when downloading Outfox.
Although it works indeed, we cannot instruct users to add their game folders as an exception on antivirus software due to the security issues this could cause if a less tech savvy player accidentally downloads a compromised simfile, for example.

**Comment by axu2** [comment]
Ah ok, just wanted to know if it was possible to avoid this Windows 10 issue on the dev side.
