### ISSUE TITLE
[Nitpick] Default theme does not have option to allow user to select characters

### ISSUE THREAD

**Issue by GravityEcho** [TeamRizu/OutFox#339]
WINDOWS 10 64 BIT 

OutFox-alpha.4.9.8
THEME: DEFAULT (SOUNDWAVES 4.9.8)

DEFAULT THEME DOES NOT ALLOW USER TO SELECT CHARACTER DESPITE CHARACTER SELECT OPTION CHOSEN.
ALSO CHARACTER IS TOO SMALL (WHEN USING RANDOM SELECTION)

USER EXPECTS RESULT OF CHOSING "SELECT" OPTION IN USER EXPERIENCE / BACKGROUND OPTIONS / DANCING CHARACTER TO (AT SOME POINT IN THE MENU LEADING UP TO SONG SELECTION) ALLOW THE USER TO SELECT A DANCING CHARACTER.

THE CHOSEN CHARACTER SHOULD THEN DANCE DURING THE SONG CHOSEN FOR GAMEPLAY BEHIND THE NOTES BUT IN FRONT OF THE RANDOM BACKGROUND MOVIE.

NOTE: CHARACTER DOES APPEAR IF "RANDOM" IS CHOSEN IN THE AFOREMENTIONED OPTION INSTEAD OF "SELECT". THIS SEEMS TO BE A COMMON THEME PROBLEM FOR STEPMANIA 5.

AN EXAMPLE OF A THEME THAT WORKS (AT LEAST SOMEWHAT) IN REGARD TO CHARACTER SELECTION IS DDR5TH THEME BY PatrickIIDX - CAN BE FOUND HERE: http://ssc.ajworld.net/?p=ddr5th

**Comment by JoseVarelaP** [comment]
This issue is a theme issue that is heavily theme creator dependent. We've considered it not necessary as not a lot of people seem to use Characters, and the Character selection on the player options is enough for now. We might consider this for a future build if there's enough demand for it.

You can still choose characters on the Player Options (hitting Start again after selecting a song).
![Captura de Pantalla 2021-05-16 a la(s) 17 54 49](https://user-images.githubusercontent.com/23246027/118415418-d2408180-b66f-11eb-832d-047a5de89451.png)


Also ironically, [the theme mentioned on the issue](http://ssc.ajworld.net/?p=ddr5th), does not even respect this rule of Characters, given it'll always load that character selection screen as long as any character is detected.

```lua
hasChars = function()
	return CHARMAN:GetAllCharacters() ~= nil
end;
...
Branch.AfterProfileLoad = function()
	-- if online, ignore character check and move straight to online
	if IsNetConnected() then ReportStyle() end;
	if IsNetSMOnline() or IsNetConnected() then
		GAMESTATE:ApplyGameCommand("playmode,regular");
		return ScreenNetSelectPlayMode()
	end

	return hasChars and "ScreenSelectCharacter" or "ScreenSelectMusic"
end
```


(Also, consider checking your caps lock when writing as it seems more alarming than necessary when everything is in caps.)

**Comment by GravityEcho** [comment]
Ah yes, please excuse the gratuitous capslock, and thank you for reading and responding. Much appreciation to you and your team. The workaround you suggested is good for now though, and thank you for suggesting it, it is helpful!
You knew right where to go in that theme code to pull out how it works, that's awesome, I had no idea, that's why users depend on you to fix these things and It sounds like you already have an idea how to go about fixing it! Wow!
I am excited about this project (capslock was too much excitement - sorry) and continued support of rhythm sims. I'm optimistic that this project will set the example and fix issues like these. So I thought if nothing is said, it may be implied users don't care but if one like me does care, others who remain silent do too. Fixing this minor issue would be a great way to show dedication to the project and the players and set outfox apart as a truly superior sim fixing a simple but long broken, neglected and annoying theme problem.

**Comment by Scraticus** [comment]
Thanks for the reply, we're trying our best :)

Closing as it looks like your problem was solved.
