### ISSUE TITLE
[BUG] Additive mines modifier breaks holds and rolls

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#353]
**Please give System Info**

OS: Windows 10 Home 64-bit (20H2)

CPU: Intel Core i7 2600 @ 3.40GHz

GPU: ATI Radeon RX 580 Series 8GB

Storage: HDD

**Please give your StepMania Info**

StepMania Version: Project OutFox 5.3 Alpha 4.9.8
Theme: Soundwaves (default, but happens everywhere)

**Describe the problem**

Upon having the "additive mines" modifier, most/all holds/rolls will break.

**Describe what should happen**

Turn the top marker (2/4) into a mine and entirely removing the connected end marker (3)
Additionally: Don't turn the end marker into a mine/step (might be the reason for this bug?)

**Logs and Additional context**

Info: [info.txt](https://github.com/TeamRizu/OutFox/files/6685100/info.txt)
Log: [log.txt](https://github.com/TeamRizu/OutFox/files/6685101/log.txt)
Video: http://y2u.be/SRwbnUgJOCQ

**Comment by Scraticus** [comment]
Thanks for reporting. 

The additive mines mod is definitely doing something weird here, I'll get back to you when we've had a look into it. It's definitely broken!

**Comment by Scraticus** [comment]
alrighty, update:

The editor may be a bit sketchy still in 4.10.0, as we are replacing it in Alpha V, so it may still play up.

We have fixed the overlaying mines and the weird way the mod seemed to ignore the 'ishold' and 'isroll' options in the step array and seemed to just place mines wherever it liked. We have modified these systems different to 5.1, as to accommodate new game modes and hold types, so the old mods on the editor haven't really been looked at in honesty, due to us replacing the editor shortly.

I'm gonna close this one as the in game issue is fixed, the editor will hopefully be done in December.

Thanks for taking the time to report this and supporting the project, it is appreciated.
