### ISSUE TITLE
[Unexpected Behavior] Song Rate

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#39]
**What you're using**

Rate and Sound Effect don't seem to be operating correctly.

**Expected behavior**

I expect one of the options in Sound Effect to proportionally change the pitch with the speed, and the other to try to keep the pitch the same. I'll call the former "LP" (because it is reminiscent of a vinyl record on the wrong RPM), and the latter "Stretch" (because FL Studio calls it that).

I propose for the third option, Off, to select between these two depending on the speed chosen. For smaller differences, LP sounds better; at the expense of different pitch, the waveform is unmodified, making the sound crisp. For extreme rates, Stretch sounds better; LP would make the song sound too muddy or tinny if the pitch were changed too. I propose using **LP if 0.7 ≤ Rate ≤ 1.5** (since Pump It Up used to have LP and a rate option between 0.8 and 1.5, and I'd like LP to also be used if Rate is 0.75).

Also, Stepmania 5's time stretching function is grating to the ears, compared to, for example, YouTube's play speed options.

**Comment by Scraticus** [comment]
This is confirmed from our voice conversation. 

The code is written so that pitch only works, or speed without pitch only works, but both sound like a wasp in a tin can.

I'll factor in a rewrite of this code to support both, though we will need to add a 'compatibility' layer for themes which do not support the new selections. 

I was able to get the desired pitch scales working fine as you saw, but in game, it was ignored, due to it dropping one or the other back to 1.0 rate.

It's gonna take a while, but it is a bug, and does need fixing.

Thanks for the report!

**Comment by JapanYoshi** [comment]
Tested Alpha 4.8.5.

**How “Speed” and “Pitch” behave:** Both behave as Stretch. Preview does not update upon changing the options.

**How “Off” behaves:** Stretch.

**Sound quality of Stretch compared to 5.1:** This may just be placebo, but I feel like the PaulStretch is better in 5.3 now.
