### ISSUE TITLE
[BUG] can't use MIDI keyboard 

### ISSUE THREAD

**Issue by Entall** [TeamRizu/OutFox#421]
OS: *Windows 10 Pro*

CPU: *AMD Ryzen 5 2600*

GPU: *AMD RX 550*

Storage: *WD HDD 1TB, ADATA Ultimate SSD 120GB*

MIDI keyboard: KORG Microkey-25

StepMania Version: Alpha 4.9.10
Theme: Native(Default)

I decided to try my MIDI keyboard in the game since they had told me that it could be used, I was playing in an earlier version (Alpha 4.9.5), I connected the keyboard and configured the buttons within the game, if it detected the MIDI keyboard but I couldn't play as it didn't detect my keystrokes, so I decided to download the new version of the game and now it doesn't even detect my MIDI keyboard. 

it is supposed to detect MIDI keyboard, be able to do button setup and play.

**Comment by Scraticus** [comment]
hiya!

This looks like you need to initialise the midi driver in your keyboard.

You need to head on over to your preference.ini file in your /save folder. 
If you installed it in portable, it will be in your game folder, otherwise it'll be in username/appdata/roaming/stepmania5.3/save

look for InputDrivers=

Add the following:

``inputdrivers=portmidi,SDL``

if the old win32_midi didn't get your midi device, the new driver should be fine.

Hope this helps!

**Comment by Scraticus** [comment]
As we didn't get a reply, we'll assume your problem is resolved. If you need more help, reopen the issue.
