### ISSUE TITLE
[BUG] 2 active players allows Double, a 1-player mode

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#47]
**What you're using**

SoundWaves theme, both player slots enter to play. Mode selection screen. Single and Solo are grayed out as intended.

**Expected behavior**

Double should be grayed out like Single and Solo, as it is a 1-player mode.

![image](https://user-images.githubusercontent.com/8707990/89031831-9f462f00-d376-11ea-8427-a5a571aaa7fd.png)

**Comment by Arcorann** [comment]
This seems to be a side effect of imitating DDR behaviour. For reference, traditionally in DDR one credit would activate Single, while two credits (pressing Start on both sides) would activate Double or Versus/Couple; there would be operator settings called "Joint Premium" or "Double Premium" that would allow the player to play Double/Versus/Couple with one credit. I can't verify right now exactly what happens when you press Start on both pads when this is set in DDR, but this is definitely how DDR behaves on normal settings.

**Comment by JapanYoshi** [comment]
I can remember that, in A and A20, the cursor locks onto Double and goes immediately to the "select payment" screen.

**Comment by Arcorann** [comment]
I should clarify that when I said "traditionally" I was thinking of DDR Extreme and earlier in particular (bearing in mind that Stepmania was developed while these games were current). I don't really know what later games do in this case, and I do agree that there should probably be an option or something to make this clearer.
