### ISSUE TITLE
[BUG] The game fails to load on Ubuntu Linux (had to manually install libopengl0)

### ISSUE THREAD

**Issue by rxhfcy** [TeamRizu/OutFox#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Linux (Ubuntu 20 LTS)

### CPU

x86_64

### Game Version

4.14.0

### Game Mode

dance

### Describe the problem

The game doesn't start at all on Ubuntu.

The error message:
./OutFox: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory

This fixes it:
sudo apt install libopengl0
(libopengl0 isn't installed by default)

### Describe what should happen

OutFox should start up on at least the major Linux distributions without requiring the user to know the right spell.

**Comment by SheepyChris** [comment]
libopengl0 is an external requirement that we do not ship with the game, since different distros maintain it differently and could result in conflicts after system updates if we shipped it. It has already been [stated in the wiki](https://outfox.wiki/user-guide/setup/install-linux/#missing-libraries) in combination with all of the other requirements necessary to run the game.
