### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by GinJones** [TeamRizu/OutFox#56]
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5025475/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5025477/log.txt)

Hello guys. Thanks for the update to OutFox, I really appreciate it. 

Outfox chrased today, I don't really know anything about errors and don't know how to read a report, but I have them uploaded in case is useful for you guys for future development. Ignore the songs that didn't have te correct format, that's solved, but, the crash continues.

Thanks and have a great day.

**Comment by Scraticus** [comment]
Hiya @GinJones!

Thanks for the report.

You need to upgrade to 4.6.0 Final as you are on a version which has known issues like the one you are reporting. This bug is actually from one of the modules we use, FFMPEG and was fixed in 4.6.0 which came out on 11th July 2020.

We also have 4.8.0 coming in a few days, so do keep an eye on our site.

I'll keep this one open until you have upgraded and got back to me to say it's all good.

**Comment by Scraticus** [comment]
Closing as seems problem is solved.
