### ISSUE TITLE
[Nitpick] USB Profiles no longer being loaded?

### ISSUE THREAD

**Issue by DarkBahamut162** [TeamRizu/OutFox#600]
### Give an example of what is wrong

I was doing stuff with it during 0.4.16 but after the update to 0.4.17 it's not working anymore.
I did the following so far so that I know that something happened between the versions.

- Checked ability to use the USB at all by going through multiple themes
- Checked Preferences.ini file on possible overwrites
- Checked usability of USB on older SM versions
- Deleted OutFox folder inside the USB for potential faulty values
- Deleted entire Save folder for sudden incompatibility

And none of them worked out in the end.

### Give an example of what it should look like

Not sure as I don't know if it had been deactivated on purpose or not.
The changelog didn't specify.

**Comment by Scraticus** [comment]
It shouldn't have been disabled, we'll look into this and try to get a fix for 4.17.1 asap.

Thanks for reporting!

**Comment by dude98** [comment]
i see that that issue started when you guys started doing the long term stable builds, and it's still not fixed by 4.18.1. It's also broken on alpha 5's builds, steam and standalone, so i'm guessing it's one of the edits from when you guys started making the LTS builds, might be a good area to check, see if anything there removed or edited the code for USB/Memory Card checking.

i hope this is fixed soon, it always felt cool to plug in a usb drive and have my profile, no matter what pc i was playing on.
sidenote: is it possible that the LTS builds were made after alpha 5's steam builds, and valve required the usb drive read/write disabled to allow it on steam? i wouldn't put it past them, as that has the possibility of being used for malicious practices.

**Comment by Scraticus** [comment]
we are currently coding a fix for this, so it should be done when we have the next releases out on all platforms, just waiting on @concubidated to confirm things so it can be properly sorted out

We haven't forgotten!

**Comment by Scraticus** [comment]
Fixed in 4.19 / 5.0.0-r32
