### ISSUE TITLE
[Game Crash] Song loading crashes every 5-10% (or so) into loading

### ISSUE THREAD

**Issue by KaeMame** [TeamRizu/OutFox#68]
Steps to reproduce:
- clean install the latest release
- start Stepmania ...
- ... Stepmania scans my songs folders and is loading everything
- Stepmania crashes
It looks like Stepmania quickly fails when there are too many files.

Sample error message (taken from the console output): Couldn't reopen "/media/blah/games/stepmaniaSongs/D3MIX COMPLETE T/d3mix/d3mix.mp3": Too many open file

I have got 255 742 items / 347.6 GB of data in my songs folders.

Hopefully, when restarting Stepmania it doesn't reload previously scanned files and resume from just before so after many restarts this eventually succeeds. I can confirm after many many restarts all gets loaded and everything eventually goes well. 33 570 songs (631 groups), 3 681 courses.

Latest release (Stepmania-Outfox-Alpha-4.8.1-amd64-date-20200814)
Ubuntu 20.04.1 LTS (uname -a says `Linux blah 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`)

Things are better on Windows 10 (4.8.1 / latest), though I did have to restart Stepmania twice for the loading to finish.

**Comment by Scraticus** [comment]
Hiya Kaede! This was a bug due to the way the new Mp3 driver was handling open file handles. I have just fixed this and another hotfix will be released shortly.

You have a long 'parsing' time due to the sheer number of songs you have, but this should not cause any bugs other than you just having to wait a few minutes. Closes #69 

Thanks again!
