### ISSUE TITLE
[Unexpected Behavior] Can't select any Advance timing window

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox#73]
This bug was reported by SillyFanBoy

**What you're using**

Stepmania 4.8.1

Trying to select any timing window that's advanced in the PlayerSongOptions makes it skip.

Video example: https://b.catgirlsare.sexy/ZPctCIpB.mp4
Log File: [log.txt](https://github.com/TeamRizu/OutFox/files/5080872/log.2.txt)

**Expected behavior**

The user should be able to select the Advanced timing window without the game skipping it.

**Comment by Scraticus** [comment]
This is due to a method that is connected with the judgement fonts.

The reporter has left the server now but I will update the issue.

On large texture loading, the game sometimes 'hangs' for a moment which can cause unintended  problems with the LUA system.

When a timing is selected by the user, the judgement font selected in the menu is loaded and then displayed to view. If this texture is huge, this can cause a 'skip' or problem with how the LUA input works, so it appears to move past the desired difficulty.

The judgement fonts used by the reporter are large, and will cause issues on slower computers. This is a bug and will be looked into as there is another system that can be used to load these judgement fonts.

**Comment by Scraticus** [comment]
This was fixed in 4.8.5, as we have been unable to replicate anymore.
