### ISSUE TITLE
[Game Crash] Won't open on Catalina

### ISSUE THREAD

**Issue by omgitsraven** [TeamRizu/OutFox#78]
**Describe how it crashed by giving us those informations:**

1. What you were doing before it crashed and what action made the game to crash.
Launching for the first time (after granting security permissions)

2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
Seems to have not gotten far enough to produce one

3. Upload the info.txt and log.txt (GameFolder/Logs)
Same; there isn't even a 'Logs' folder

**Explain how we can reproduce the error**

1. Go to 'downloads' page, and download StepMania-Outfox-Alpha-4.8.2-MacOS-date-20200819.dmg
2. Mount the DMG
3. Copy the drive to a folder in the Applications folder (I just guessed at this step; it doesn't work running off the DMG either though)
4. Double-click the StepMania.app icon
5. A prompt will tell you it can't run because of security
6. Go to System Preferences > Security & Privacy, and grant permission to 'open anyway'
7. Double-click the StepMania.app icon again
8. Click 'open' on the security prompt
9. Observe the dock; the StepMania icon appears very briefly, then vanishes without opening a window or anything.

**Sreenshots/Videos**

Nothing to screenshot, it gives up instantly.

**Additional information**

I'm running macOS 10.15.5 on an Early 2014 MacBook Air

**Comment by JoseVarelaP** [comment]
The application won't run just by allowing on the security prompt. Apple prevents unsigned applications from running unless you revoke them from the quarantined zone. For now, you can do the following:

+ Open a terminal window
+ Type  `xattr -dr com.apple.quarantine /path/to/outfox`.
(You can alternatively type `xattr -dr com.apple.quarantine`, followed by a space, and then drag the folder where you've installed OutFox.

If the terminal does not report anything after pressing enter, then you should be good to go.

As for step 3 of your procedure process, that's not the intended method to run the game. MacOS applications cannot run from within the image because those images are read only, so they're never able to write information onto it, so you have to extract it.

**Comment by omgitsraven** [comment]
The xattr command did it! Thank you!
